ContentUploader/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.index,name='home'),
    # path('hall_list/<str:location>/',views.hall_on_location,name='hall_on_location'),
    path('dashboard/administrator/',views.administrator_dashboard,name='administrator_dashboard'),
    path('dashboard/customer/',views.customer_dashboard,name='customer_dashboard'),
    path('dashboard/hall/',views.hall_dashboard,name='hall_dashboard'),
    path("detail/marriagehall/<int:pk>/",views.HallDetailView,name='hall-detail'),
    path("marriagehall/<int:pk>/update/",views.HallUpdateView.as_view(),name='hall-update'),
    path("marriagehall/<int:pk>/delete/",views.HallDeleteView.as_view(),name='hall-delete'),
    path('admin/dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path("upload/marriagehall/content/",views.HallCreationView.as_view(),name='create-hall'),
    path("marriagehall/content/<int:pk>/",views.upload_hall_content,name='upload-content'),
    path("marriagehall/content/delete/image",views.deletehallimage,name='hall-image-delete'),
    path("marriagehall/content/delete/video",views.deletehallvideo,name='hall-video-delete'),


    # deleted by admin

    path("admin/delete/<str:rolename>/<int:id>/",views.deleted_by_admin,name="deleted_by_admin")
]

hotelProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include,re_path
from bookings import views as booking_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ContentUploader.urls')),
    path('accounts/',include('users.urls')),
    
    path("marriagehall_booking/<int:pk>/",booking_views.HallBookingOnLocation,name='hall-booking'),
    path('set_custom_booking/<int:pk>/',booking_views.SetCustomBooking,name='set_custom_booking'),
    path('set_custom_booking/new_customer/<int:pk>/',booking_views.SetCusBookWithNcust,name='set_custom_booking_with_ncustomer'),
    path('set_custom_booking/exsisting_customer/<int:pk>/',booking_views.SetCusBookWithEcust,name='set_custom_booking_with_ecustomer'),    

    path('check_user/',booking_views.check_user,name='check_user'),
    path('check_customer_user/',booking_views.check_customer_user,name='check_customer_user'),
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('customer_register/',views.CustomerUserRegister,name='customer_register'),
    


    path('administrator_register/',views.AdministratorUserRegister,name='administrator_register'),
    path('hall_register/',views.HallUserRegister,name='hall_register'),
    path('register/verification_token/',views.verification_info,name='verification_info'),
    path('verify/<auth_token>/<int:id>/',views.verify,name='verify'),
    path('profile/',views.profile,name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),

    # password reset routes
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
]

ContentUploader/models.py
from django.db import models
from users.models import Administrator,HallManager,Customer
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from PIL import Image

# Create your models here.

class MarriageHall(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    price = models.PositiveIntegerField(null=True,blank=True)
    owner = models.ForeignKey(HallManager,on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('hall-detail' , kwargs={'pk':self.pk})

    
        



class HallImages(models.Model):
    image=models.ImageField(upload_to='hall_images',default="prepared_wedding_hall.jpg")
    image_alt = models.CharField(max_length=255)
    hall=models.ForeignKey(MarriageHall,on_delete=models.CASCADE)

    def __str__(self):
        return self.image.name
    

    # def save(self,*args,**kwargs):
    #     super().save(*args,**kwargs)  # saving image first

    #     img = Image.open(self.image.path) # Open image using self

    #     if img.height > 300 or img.width > 300:
    #         new_img = (300, 300)
    #         img.thumbnail(new_img)
    #         img.save(self.image.path)  # saving image at the same path


class HallVideos(models.Model):
    video = models.FileField(upload_to='hall_videos',null=True,validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])
    hall=models.ForeignKey(MarriageHall,on_delete=models.CASCADE)

    def __str__(self):
        return self.video.name


    


    
    
            

bookings/models.py
from django.db import models
from ContentUploader.models import MarriageHall
from users.models import Customer

# Create your models here.


class Booking(models.Model):
    marriagehall = models.ForeignKey(MarriageHall, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()
    booked_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.marriagehall.title} is booked from {self.check_in} to {self.check_out}'

ContentUploader/forms.py
from django import forms
from .models import MarriageHall,Booking

class HallContentUploadingForm(forms.ModelForm):
    class Meta:
        model=MarriageHall
        fields=['title','description','location','price','owner']

bookings/forms.py
from django import forms




class CustomLoginForm(forms.Form):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Username'}))




class BookingForm(forms.Form):
    check_in = forms.DateTimeField(required=True,input_formats=["%Y-%m-%dT%H:%M",])
    check_out = forms.DateTimeField(required=True,input_formats=["%Y-%m-%dT%H:%M",])

ContentUploader/views.py
from typing import Dict
from django.shortcuts import redirect, render,HttpResponse
from users.decorators import customer_required,administrator_required,hallmanager_required,admin_required
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import CreateView,UpdateView,DeleteView
from .models import MarriageHall,HallImages,HallVideos
from django.contrib import messages
from django.utils.decorators import method_decorator
from users.models import Customer,Administrator,HallManager,User
from django.db.models import Q
from bookings.models import Booking




# Create your views here.

def index(request):
    location=request.GET.get('location')
    if location:
        location = location.lower()
        all_hall_on_location=MarriageHall.objects.filter(
            Q(location__icontains=location) |
            Q(title__icontains=location) |
            Q(description__icontains=location)).all()
        if not all_hall_on_location:
            messages.success(request,f'{location} is not listed yet :(. Please search another!')
            return redirect('home')
        context={'location':location,'all_hall_on_location':all_hall_on_location}
        return render(request,'ContentUploader/hall_list_on_location.html',context)
    
    

    return render(request,'ContentUploader/index.html')




@administrator_required
def administrator_dashboard(request):
    all_halls=MarriageHall.objects.all()
    all_hall_profiles=HallManager.objects.all()
    profile_with_no_hall=[]
    for profile in all_hall_profiles:
        if(profile.marriagehall_set.all().count()==0):
            profile_with_no_hall.append(profile)

    context={
            'all_halls':all_halls,
            'profile_with_no_hall':profile_with_no_hall,
        }
    return render(request,'ContentUploader/administrator_dashboard.html',context)




@hallmanager_required
def hall_dashboard(request):
    ahfcu=MarriageHall.objects.filter(owner=request.user.hallmanager).all()
    manager = HallManager.objects.filter(user=request.user).first()
    context={
        'a_halls_fcu':ahfcu,
        'manager':manager,
    }
    return render(request,'ContentUploader/hallmanager_dashboard.html',context)


@customer_required
def customer_dashboard(request):
    customer=Customer.objects.filter(user=request.user).first()
    _customer_bookings=Booking.objects.filter(customer=customer).all()
    context={
        'all_cus_bookings':_customer_bookings,
    }
    return render(request,'ContentUploader/customer_dashboard.html',context)



       

@admin_required
def admin_dashboard(request):
    all_hall_managers=HallManager.objects.all()
    all_administrators=Administrator.objects.all()
    all_bookings=Booking.objects.all()
    all_marriage_halls=MarriageHall.objects.all()
    
    context={
        'all_hall_managers':all_hall_managers,
        'all_administrators':all_administrators,
        'all_bookings':all_bookings,
        'all_marriage_halls':all_marriage_halls,
    }

    return render(request,'ContentUploader/admin_dashboard.html',context)



@method_decorator(administrator_required, name='dispatch')
class HallCreationView(LoginRequiredMixin,CreateView):
    model = MarriageHall
    fields=['title','description','location','price','owner']
    template_name = 'ContentUploader/create_hall.html'

    def form_valid(self,form):
        return super().form_valid(form)
    

@administrator_required
def upload_hall_content(request,pk):
    marriage_hall=MarriageHall.objects.filter(id=pk).first()
    marr_img_alt=marriage_hall.title
    if(request.method=='POST'):
        images=request.FILES.getlist('images')
        for image in images:
            img=HallImages.objects.create(image=image,image_alt=marr_img_alt,hall=marriage_hall)
            img.save()
        videos=request.FILES.getlist('videos')
        for video in videos:
            vid=HallVideos.objects.create(video=video,hall=marriage_hall)
            vid.save()
        return redirect('hall-detail',pk=marriage_hall.id)
    context={
        'object':marriage_hall,
        'videos':marriage_hall.hallvideos_set.all(),
        'images':marriage_hall.hallimages_set.all(),
    }
    return render(request,'ContentUploader/marriage_hall_detail.html',context)




def HallDetailView(request,pk):
    marriagehall=MarriageHall.objects.filter(pk=pk).first()
    context={
        'marriagehall':marriagehall,
    }
    return render(request,'ContentUploader/marriage_hall_detail.html',context)



@administrator_required
def deletehallimage(request):
    if request.method=='POST':
        try:
            image_str=request.POST.get('delimage')
            getImage=HallImages.objects.get(id=int(image_str))
            hall=getImage.hall
            getImage.delete()
        except Exception as e:
            messages.success(request,f'Technical Error occured')
        return redirect('hall-detail',pk=hall.id)
    # return redirect('home')
    return render(request,'ContentUploader/index.html')

@administrator_required
def deletehallvideo(request):
    if request.method=='POST':
        try:
            video_str=request.POST.get('delvid')
            getVideo=HallVideos.objects.get(id=int(video_str))
            hall=getVideo.hall
            getVideo.delete()
        except Exception as e:
            messages.success(request,f'Technical Error occured')
        return redirect('hall-detail',pk=hall.id)
    # return redirect('home')
    return render(request,'ContentUploader/index.html')


@method_decorator(administrator_required, name='dispatch')
class HallUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = MarriageHall
    fields=['title','description','location','price']
    template_name = 'ContentUploader/create_hall.html'    
    
    def form_valid(self,form):
        form.instance.administrator=self.request.user.administrator
        return super().form_valid(form)
    
    def test_func(self):
        hall=self.get_object()
        if self.request.user.administrator==hall.administrator:
            return True
        return False



@method_decorator(administrator_required, name='dispatch')
class HallDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = MarriageHall
    template_name = 'ContentUploader/marriage_hall_delete.html'
    success_url='/'
    def test_func(self):
        hall=self.get_object()
        if self.request.user.administrator==hall.administrator:
            return True
        return False
    


@admin_required
def deleted_by_admin(request,rolename,id):
    if request.user.is_admin:
        if rolename == "administrator":
            tobedeleted = User.objects.get(id=id)
            if tobedeleted:
                messages.success(request,f'{tobedeleted.user.username} deleted successfully!')
                tobedeleted.delete()
                return redirect("admin_dashboard")
        elif rolename == "hallmanager":
            tobedeleted = User.objects.get(id=id)
            if tobedeleted:
                messages.success(request,f'{tobedeleted.user.username} deleted successfully!')
                tobedeleted.delete()
                return redirect("admin_dashboard")
        
        elif rolename == "booking":
            tobedeleted = Booking.objects.get(id=id)
            if tobedeleted:
                messages.success(request,f'{tobedeleted} deleted successfully!')
                tobedeleted.delete()
                return redirect("admin_dashboard")
        elif rolename == "marHall":
            tobedeleted = Booking.objects.get(id=id)
            if tobedeleted:
                messages.success(request,f'{tobedeleted.title} deleted successfully!')
                tobedeleted.delete()
                return redirect("admin_dashboard")

    
    return HttpResponse("DONE")

ContentUploader/templates/ContentUploader/administrator_dashboard.html
{% extends 'ContentUploader/base.html' %}
{% block title %}
Dashboard
{% endblock title %}
{% load static %}
{% block withoutcontainer %}

<style>
    .hall>p {
        font-size: 0.9rem;
        padding-right: 20px;
    }
</style>
<div class="row">
    <div class="col-md-2 sidebar">
        <div class="">
            <ul class='dashul'>
                <li><span><i class="fa fa-home" aria-hidden="true"></i></span><a
                    href="{% url 'home' %}">Home</a></li>
                <li><span><i class="fa fa-tachometer-slow" aria-hidden="true"></i></span><a
                        href="#dashboard">Dashboard</a></li>
                <li><span><i class="fa fa-user" aria-hidden="true"></i></span><a href="#allhalls">All Halls</a></li>
                <li><span><i class="fa fa-user" aria-hidden="true"></i></span><a href="#uploadnew">Upload New Hall</a>
                </li>

            </ul>
        </div>
    </div>
    <div class="col-md-10 right_side_bar pt-4">

        <div id="dashboard">
            <p class="h3 py-1">Dashboard</p>
        </div>
        <div class="text-center" style="background-color:var(--bs-gray-500);color: var(--bs-gray-100);" id='allhalls'>
            <p class="h3 text-center border py-1">All Marriage Halls </p>
        </div>


        <div class="mt-5">
            {% for hall in all_halls %}
            <div class="ml-4 mb-3 hall">
                <a href="{% url 'hall-detail' hall.pk %}">
                    <p class="h4">{{hall.title}}</p>
                </a>
                <p>{{hall.description}}</p>

            </div>
            {% endfor %}
        </div>

        <div id="uploadnew" class="text-center mt-5" style="background-color:var(--bs-gray-500);color: var(--bs-gray-100);">
            <p class="h3 text-center border py-1">Upload New Hall Content</p>
        </div>

        <a href="{% url 'create-hall' %}" class="btn btn-primary my-2" target="_blank">
            Upload Content
        </a>
        <ul class="list-group my-3">
            <p class="h5">Hall-Profile with no content uploaded yet......</p>
            {% for profile in profile_with_no_hall %}

            <li class="list-group-item">{{ profile }}</li>
            {% endfor %}
        </ul>

    </div>



</div>


{% endblock withoutcontainer %}

ContentUploader/templates/ContentUploader/create_hall.html
{% extends 'ContentUploader/base.html' %}
{% block title %}
Upload Hall Content
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="my-3">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <legend class='border-bottom mb-4 pb-3'>Create Marriage Hall</legend>
    
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class='btn btn-outline-primary my-3'>Create</button>
        </div>
    </form>
</div>

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyCFhkZ0QFEWyJeiaop7d5FPC82fvzQlnAw"></script>
<script>
    var mylocation = document.querySelector("#id_location")
    var autocomplete;
    autocomplete = new google.maps.places.Autocomplete(mylocation),{
        types : ['geocode'],
    }

</script>
{% endblock content %}

ContentUploader/templates/ContentUploader/hallmanager_dashboard.html
{% extends 'ContentUploader/base.html' %}
{% block title %}
Dashboard
{% endblock title %}
{% load static %}
{% block withoutcontainer %}

<style>
    .hall>p {
        font-size: 0.9rem;
        padding-right: 20px;
    }
</style>

<div class="create_c_and_b">
    <a href="{% url 'set_custom_booking' manager.id  %}" target="_blank" style="z-index:100;">
        <img src="{% static 'ContentUploader/images/plus_icon.png' %}" alt="set custom booking" style="width: 50px;">
    </a>
</div>
<div class="row">
    <div class="col-md-2 sidebar">
        <div class="">
            <ul class='dashul'>
                <li><span><i class="fa fa-home" aria-hidden="true"></i></span><a href="{% url 'home' %}">Home</a></li>
                <li><span><i class="fa fa-tachometer-slow" aria-hidden="true"></i></span><a
                        href="#dashboard">Dashboard</a></li>
                <li><span><i class="fa fa-hotel" aria-hidden="true"></i></span><a href="#allhalls">My Halls</a></li>
                <li><span><i class="fa fa-calendar-times" aria-hidden="true"></i></span><a href="#mybookings">My
                        Bookings</a>
                </li>

            </ul>
        </div>
    </div>
    <div class="col-md-10 right_side_bar pt-4">

        <div id="dashboard">
            <p class="h3 py-1">Dashboard</p>
        </div>


        <!-- All my marriage halls -->
        <div class="text-center" style="background-color:var(--light-blue);color: white;" id='allhalls'>
            <p class="h3 text-center border py-1">My Marriage Halls</p>
        </div>
        <table class="table table-responsive">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">No. of Bookings</th>

                </tr>
            </thead>
            <tbody>
                {% for hall in a_halls_fcu %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{hall.title}}</td>

                    <td>{{hall.booking_set.all.count}}</td>
                </tr>
                {% endfor %}

            </tbody>
        </table>



        <!-- All my bookings -->
        <div class="text-center mt-5" style="background-color:var(--light-blue);color: white;"
            id='mybookings'>
            <p class="h3 text-center border py-1">Booking Details</p>
        </div>
        <table class="table table-responsive">
            <thead class="thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Marriage hall</th>
                    <th scope="col">Starting From</th>
                    <th scope="col">Ending At</th>
                    <th scope="col">Customer</th>
                </tr>
            </thead>
            <tbody>
                {% for hall in a_halls_fcu %}
                {% for booking in hall.booking_set.all %}

                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{booking.marriagehall.title}}</td>
                    <td>{{booking.check_in}}</td>
                    <td>{{booking.check_out}}</td>
                    <td>{{booking.customer.user.username}}</td>
                </tr>
                {% endfor %}
                {% endfor %}

            </tbody>
        </table>




    </div>



</div>


{% endblock withoutcontainer %}

ContentUploader/templates/ContentUploader/marriage_hall_delete.html
{% extends 'ContentUploader/base.html' %}
{% block title %}
Delete Hall
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">

    <form action="" method="POST">
        {% csrf_token %}
        <fieldset>
            <legend class='border-bottom mb-4 pb-3'>Delete Marriage Hall</legend>
            <h2>Are you really want to delete this marriage hall "{{ object.title }}" ?</h2>
        </fieldset>
        <div class="form-group">
            <button type="submit" class='btn btn-outline-danger my-3'>Yes, Delete </button>
            <a class='btn btn-outline-secondary my-3' href="{% url 'hall-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>


{% endblock content %}

ContentUploader/templates/ContentUploader/marriage_hall_detail.html
{% extends 'ContentUploader/base.html' %}
{% block title %}
Hall Detail Content
{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

<style>
    .myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

    .myImg:hover {
        opacity: 0.7;
    }

    /* The Modal (background) */
    .modal {
        display: none;
        /* Hidden by default */
        position: fixed;
        /* Stay in place */
        z-index: 1;
        /* Sit on top */
        padding-top: 100px;
        /* Location of the box */
        left: 0;
        top: 0;
        width: 100%;
        /* Full width */
        height: 100%;
        /* Full height */
        overflow: auto;
        /* Enable scroll if needed */
        background-color: rgb(0, 0, 0);
        /* Fallback color */
        background-color: rgba(0, 0, 0, 0.9);
        /* Black w/ opacity */
    }

    /* Modal Content (image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    /* Caption of Modal Image */
    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    /* Add Animation */
    .modal-content,
    #caption {
        -webkit-animation-name: zoom;
        -webkit-animation-duration: 0.6s;
        animation-name: zoom;
        animation-duration: 0.6s;
    }

    @-webkit-keyframes zoom {
        from {
            -webkit-transform: scale(0)
        }

        to {
            -webkit-transform: scale(1)
        }
    }

    @keyframes zoom {
        from {
            transform: scale(0)
        }

        to {
            transform: scale(1)
        }
    }

    /* The Close Button */
    .close {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

    .close:hover,
    .close:focus {
        color: #bbb;
        text-decoration: none;
        cursor: pointer;
    }

    /* 100% Image Width on Smaller Screens */
    @media only screen and (max-width: 700px) {
        .modal-content {
            width: 100%;
        }
    }
</style>


{% if user.is_customer %}
<div class="chat-anim-btn">
    <a href="https://wa.me/{{ marriagehall.owner.phone_number }}" target="_blank" style="z-index:100;">
        <img src="{% static 'ContentUploader/images/whatsapp.png' %}" alt="" style="width: 70px;">
    </a>
</div>
    
{% endif %}

<div class="row my-5">
    {% for video in marriagehall.hallvideos_set.all %}
    <div class="col-md-6" style="position: relative;">
        <video width="400" controls class="w-100" class="w-100">
            <source src="{{video.video.url}}" type="video/mp4">
            Your browser does not support HTML5 video.

        </video>

        {% if user.is_administrator %}
        <form action="{% url 'hall-video-delete' %}" method='post' enctype="multipart/form-data"
            style="position:absolute; top:-13px;right:-5px;">
            {% csrf_token %}
            <input type="hidden" value="{{ video.id }}" name='delvid'>
            <button type="submit" style="border: none; background-color: rgba(255, 255, 255, 0);">
                <i class="fas fa-times-circle" style="font-size: 25px; color: black;"></i>
            </button>
        </form>
        {% endif %}
    </div>
    {% endfor %}
    <div class="col-md-6">
        <div class="row">

            {% for image in marriagehall.hallimages_set.all %}
            <div class="col-md-4 mb-4">

                <img class="myImg" src="{{ image.image.url }}" alt="{{ image.image_alt }}"
                    style="width:100%;max-width:300px">

                {% if user.is_administrator %}
                <form action="{% url 'hall-image-delete' %}" method="post" enctype="multipart/form-data"
                    style="position:absolute; top:-15px;right:-7px;">
                    {% csrf_token %}
                    <input type="hidden" value="{{ image.id }}" name='delimage'>
                    <button type="submit" style="border: none; background-color: rgba(255, 255, 255, 0);">
                        <i class="fas fa-times-circle" style="font-size: 25px; color: black;"></i>
                    </button>
                </form>
                {% endif %}
            </div>


            {% endfor %}
        </div>


        <!-- The Modal -->
        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <img class="modal-content" id="img01">
            <div id="caption"></div>
        </div>
    </div>


</div>





<div class="container">

    <a class="mr-2" href="#">Owner : {{ marriagehall.owner.user.username }}</a>

    <div class="row">
        <div class="col-md-8">
            <h2 class='article-title'>{{ marriagehall.title }}</h2>
            <!-- {{ post.title }} -->
            <p class="article-content" style="font-size: 0.9rem;text-align: justify;">{{ marriagehall.description }}</p>
        </div>


        <div class="col-md-4">
            {% if user.is_customer %}
                
            <div class="border p-4 mb-3">
                <h3 class="text-center ">Set Booking</h3>
                <form action="{% url 'hall-booking' marriagehall.id %}" method="post">
                    {% csrf_token %}
                    <label for="id_check_in">
                        Check In
                    </label>
                    <input type="datetime-local" name="checkin" id="id_check_in" class="form-control">
                    <label for="id_check_out">
                        Check Out
                    </label>
                    <input type="datetime-local" name="checkout" id="id_check_out" class="form-control">

                    <button type="submit" class="btn btn-primary my-4 btn-block">Book Now</button>

                </form>
            </div>
            {% endif %}
        </div>

    </div>
</div>
<div class="container">


    {% if user.is_administrator %}
    <div class="my-4">
        <form action="{% url 'upload-content' marriagehall.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="my-2">
                <label for="images">Upload Images</label><br>
                <input type="file" name="images" id="images" multiple accept="image/*"><br>
            </div>
            <div class="my-2">
                <label for="videos">Upload Videos</label><br>
                <input type="file" name="videos" id="videos" multiple accept="video/*"><br>
            </div>
            <button type="submit" class="btn btn-primary my-2">Save Media</button>
        </form>

        <hr>
    </div>
    {% endif %}
    {% if user.is_administrator %}
    <div>
        <a class="btn btn-secondary btn-sm my-1 link-light my-4"
            href="{% url 'hall-update' marriagehall.id %}">Update</a>

    </div>

    {% endif %}
</div>


<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementsByClassName("myImg");
    var modalImg = document.getElementById("img01");
    var captionText = document.getElementById("caption");
    for (let index = 0; index < img.length; index++) {
        const element = img[index];
        element.onclick = function () {
            modal.style.display = "block";
            modalImg.src = this.src;
            captionText.innerHTML = this.alt;
        }
    }


    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }
</script>




{% endblock content %}